[package]
name = "lpc1347"
version = "0.2.0"
authors = ["Axel Sundbom <axel-sundbom@hotmail.com>"]
description = "Peripheral access for the nxp lpc1347"

[dependencies]
cortex-m = "^0.4.0"
bare-metal = "0.1.0"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "^0.4.0"

[features]
rt = ["cortex-m-rt"]

[package.metadata.docs.rs]
features = ["rt"]
